USE [master]
GO



IF DB_ID('Tools') IS NOT NULL
BEGIN
DROP DATABASE[Tools]
END


PRINT 'Creating Database'
CREATE DATABASE [Tools]
 ON  PRIMARY 
( NAME = N'Tools', FILENAME = N'E:\MSSQL\DATA\Tools.mdf' , SIZE = 3174400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'Tools_log', FILENAME = N'L:\MSSQL\LOGS\Tools_log.ldf' , SIZE = 1280000KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
GO
PRINT 'Database Created'



PRINT 'Configuring Database'

DECLARE @ErrorNumber AS INT, 
@ErrorMessage AS NVarchar(1000), 
@error_severity AS INT


IF (SELECT CONVERT(NVARCHAR,SERVERPROPERTY('ProductVersion'))) LIKE '13%'
ALTER DATABASE Tools SET COMPATIBILITY_LEVEL = 130
IF (SELECT CONVERT(NVARCHAR, SERVERPROPERTY('ProductVersion'))) LIKE '12%'
ALTER DATABASE Tools SET COMPATIBILITY_LEVEL = 120
IF (SELECT CONVERT(NVARCHAR, SERVERPROPERTY('ProductVersion'))) LIKE '11%'
ALTER DATABASE Tools SET COMPATIBILITY_LEVEL = 110
IF (SELECT CONVERT(NVARCHAR, SERVERPROPERTY('ProductVersion'))) LIKE '10%'
ALTER DATABASE Tools SET COMPATIBILITY_LEVEL = 100



IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC Tools.[dbo].[sp_fulltext_database] @action = 'enable'
END


ALTER DATABASE Tools SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE Tools SET ANSI_NULLS OFF 


ALTER DATABASE Tools SET ANSI_PADDING OFF 


ALTER DATABASE Tools SET ANSI_WARNINGS OFF 


ALTER DATABASE Tools SET ARITHABORT OFF 

ALTER DATABASE Tools SET AUTO_CLOSE OFF 


ALTER DATABASE Tools SET AUTO_SHRINK OFF 


ALTER DATABASE Tools SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE Tools SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE Tools SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE Tools SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE Tools SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE Tools SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE Tools SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE Tools SET  DISABLE_BROKER 


ALTER DATABASE Tools SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE Tools SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE Tools SET TRUSTWORTHY OFF 

ALTER DATABASE Tools SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE Tools SET PARAMETERIZATION SIMPLE 

ALTER DATABASE Tools SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE Tools SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE Tools SET RECOVERY FULL 

ALTER DATABASE Tools SET  MULTI_USER 

ALTER DATABASE Tools SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE Tools SET DB_CHAINING OFF 

ALTER DATABASE Tools SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE Tools SET TARGET_RECOVERY_TIME = 0 SECONDS 

ALTER DATABASE Tools SET  READ_WRITE 



PRINT 'Configuration Complete'

GO